DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS(
ID serial PRIMARY KEY, NAME VARCHAR(50), ADDRESS VARCHAR(50), POSTAL_CODE INT, CITY VARCHAR(50)
);

INSERT INTO
  CUSTOMERS (NAME, ADDRESS, POSTAL_CODE, CITY)
VALUES
  ('Test AB', 'ABC123', 11111, 'Stockholm'),
  ('Test1 AB', 'DEF456', 11111, 'Goteborg'),
  ('Test2 AB', 'GHI789', 11111, 'Malmo');