DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS(
ID serial PRIMARY KEY, NAME VARCHAR(50), ADDRESS VARCHAR(50), POSTAL_CODE INT, CITY VARCHAR(50)
);

INSERT INTO
  CUSTOMERS (ID, NAME, ADDRESS, POSTAL_CODE, CITY)
VALUES
  (1,'Test AB', 'ABC123', 11111, 'Stockholm'),
  (2,'Test1 AB', 'DEF456', 11111, 'Goteborg'),
  (3,'Test2 AB', 'GHI789', 11111, 'Malmo');