DROP TABLE IF EXISTS APPLIANCES;

CREATE TABLE APPLIANCES(
ID SERIAL PRIMARY KEY, APPLIANCE_ID VARCHAR(50), FACTORY_NUMBER VARCHAR(50), OWNER_ID INTEGER, LAST_CONNECTION_PING TIMESTAMP
);

INSERT INTO
  APPLIANCES (APPLIANCE_ID, FACTORY_NUMBER, OWNER_ID, LAST_CONNECTION_PING)
VALUES
  ('YS2401', 'ABC123', 1, CURRENT_TIMESTAMP),
  ('VLU588', 'DEF456', 2, CURRENT_TIMESTAMP),
  ('VLU066', 'GHI789', 3, CURRENT_TIMESTAMP);