DROP TABLE IF EXISTS APPLIANCES;

CREATE TABLE APPLIANCES(
ID serial PRIMARY KEY, APPLIANCE_ID VARCHAR(50), FACTORY_NUMBER VARCHAR(50), OWNER_ID INTEGER, LAST_CONNECTION_PING TIMESTAMP
);

INSERT INTO
  APPLIANCES (ID, APPLIANCE_ID, FACTORY_NUMBER, OWNER_ID, LAST_CONNECTION_PING)
VALUES
  (1,'YS2401', 'ABC123', 1, CURRENT_TIMESTAMP),
  (2,'VLU588', 'DEF456', 2, CURRENT_TIMESTAMP),
  (3,'VLU066', 'GHI789', 3, CURRENT_TIMESTAMP);